sonar.projectKey=ElenaTomasVela_GlassParrot
sonar.organization=elenatomasvela

sonar.javascript.lcov.reportPaths=./coverage/lcov.info
# Keep test results separate from Sonar results
sonar.qualitygate.wait=false 

# Files that should not be tested for coverage
# NOTE: Worker files do not work with coverage. Do not include.
sonar.coverage.exclusions= **/*.tsx,\
  **/*.test.ts,\
  src/lib/modelPresets.ts,\
  src/lib/languageModel/languageModel.ts, \
  src/lib/languageModel/modelTrainingWorker.ts \
