sonar.projectKey=ElenaTomasVela_GlassParrot
sonar.organization=elenatomasvela

sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.qualitygate.wait=true

# Files that should not be tested for coverage
sonar.coverage.exclusions= **/*.tsx,\
  **/*.test.ts,\
  src/lib/modelPresets.ts,\
  src/lib/languageModel/languageModel.ts
